rm(list=ls())
load('../DEseq2/res_deseq_Fm_WT.RData')
l_all_genes<-unique(rownames(res))
library(biomaRt)
mart <- useMart('ENSEMBL_MART_ENSEMBL', dataset='mmusculus_gene_ensembl')
ensemble2entrez<-getBM(attributes = c('ensembl_gene_id','entrezgene_id'),filters = 'ensembl_gene_id',values = l_all_genes,mart=mart)
ensemble2symbol<-getBM(attributes = c('ensembl_gene_id','mgi_symbol'),filters = 'ensembl_gene_id',values = l_all_genes,mart=mart)
ensembl2entrez2symbol<-merge(ensemble2entrez,ensemble2symbol,by='ensembl_gene_id')
write.table(ensembl2entrez2symbol,'ensembl2entrez2symbol.map',row.names = F,quote = F)
